version: '3.3'
services:
  migrate:
    image: migrate/migrate
    volumes:
      - ./schema:/var/schema
    command: ["-path", "/var/schema", "-database",  "mysql://root:Hui2oe7thaeshin1oohai5bi9@tcp(18.223.237.146:3306)/library", "up"]
