name: MySQL Migrations

on: [push]

jobs:
  migration:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code from the repository
        uses: actions/checkout@v2
      - name: list
        run: |
          ls -l
          ls -l ./migrate/schema/
          cd ./migrate/; docker-compose up




